### ISSUE TITLE
Segfault on repeated clicks. 

### ISSUE THREAD

**Issue by andrewbest-tri** [ToyotaResearchInstitute/gauges2#25]
I can replicate with the throttle and break as well as steering.

Reproduction instructions:
1) add steering wheel to rqt
2) subscribe to topic (make sure data is playing)
3) click into the numerical gauge to resize
-> Segfault

Looking at it. this could an out of range type of exception as the default value for the widget is 45 degrees which is very small for a hweel angle. (+/- 540 for most wheels)

I'll post a video to slack

**Comment by ahcorde** [comment]
I made some changes in this PR https://github.com/ToyotaResearchInstitute/gauges2/pull/30 (already merged). 

The problem was try to update the GUI from a ROS thread/callback
