### ISSUE TITLE
/ character breaks autocomplete

### ISSUE THREAD

**Issue by andrewbest-tri** [ToyotaResearchInstitute/gauges2#27]
The / character breaks the autocomplete when selecting data channels. So, it becomes really difficult to filter on channels within a namespace since I must try to autocomplete top level only.

 Example

"/foo" would show 
"/foo/bar"
"/foo/baz"

but "/foo/"
show nothing and 
"/foo/b"

shows nothing

**Comment by ahcorde** [comment]
This PR https://github.com/ros-visualization/rqt/pull/299 in `rqt_py_common` fixes this issue

**Comment by ahcorde** [comment]
PR is merged, @andrewbest-tri feel free to reopen the issue if the problem persists

PR was also backported to Humble and Iron
