### ISSUE TITLE
Speedometer widget being re-sizable

### ISSUE THREAD

**Issue by francocipollone** [ToyotaResearchInstitute/gauges2#5]
### Summary

It would be great if the speedometer gets dynamically adjusted when the window gets bigger or smaller

![image](https://user-images.githubusercontent.com/53065142/225640737-9a124e4b-266b-49e4-84b8-454e74db4f6d.png)

**Comment by ahcorde** [comment]
Related PR https://github.com/ToyotaResearchInstitute/gauges2/pull/22
